### PR TITLE
Fix synthetic filelist not being uploaded

### LINKED ISSUE #2506: Expected there to be a temporary fileset for synthetic filelist
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.56
**Operating System:** QNAP - Linux
**Backend:** Linux

### Bug Description 

I got this error when I run an Backup. 

### Steps to reproduce
- Starr a Backup

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### debug log
DeletedFiles: 0
DeletedFolders: 0
ModifiedFiles: 1321
ExaminedFiles: 2792
OpenedFiles: 1395
AddedFiles: 74
SizeOfModifiedFiles: 102369729
SizeOfAddedFiles: 267267633
SizeOfExaminedFiles: 15278576024
SizeOfOpenedFiles: 8032101584
NotProcessedFiles: 0
AddedFolders: 0
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults: null
DeleteResults: null
RepairResults: null
TestResults:
    MainOperation: Test
    Verifications: [
        Key: duplicati-20170104T135943Z.dlist.zip.aes
        Value: [],
        Key: duplicati-i376bbec0de2d48b1a635bc1e92272b1f.dindex.zip.aes
        Value: [],
        Key: duplicati-bba40cac5e8e04492b714bdd38f512ba1.dblock.zip.aes
        Value: []
    ]
    ParsedResult: Success
    EndTime: 5/26/2017 11:12:49 PM
    BeginTime: 5/26/2017 11:12:09 PM
    Duration: 00:00:40.0580100
    BackendStatistics:
        RemoteCalls: 10
        BytesUploaded: 146015489
        BytesDownloaded: 105765895
        FilesUploaded: 5
        FilesDownloaded: 3
        FilesDeleted: 0
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 311
        KnownFileSize: 14579977579
        LastBackupDate: 5/27/2017 1:00:00 AM
        BackupListCount: 15
        TotalQuotaSpace: 0
        FreeQuotaSpace: 0
        AssignedQuotaSpace: -1
        ParsedResult: Success
ParsedResult: Warning
EndTime: 5/26/2017 11:12:49 PM
BeginTime: 5/26/2017 11:00:00 PM
Duration: 00:12:49.5599190
Messages: [
    scheduling missing file for deletion, currently listed as Uploading: duplicati-20170526T071003Z.dlist.zip.aes,
    promoting uploaded complete file from Uploading to Uploaded: duplicati-ida79c3f2d3c4449c9b36cde7b6aec699.dindex.zip.aes,
    scheduling missing file for deletion, currently listed as Uploading: duplicati-b8b56137049844b79a9c31a43110bdc04.dblock.zip.aes,
    scheduling missing file for deletion, currently listed as Uploading: duplicati-ie7e0ca0276104444967b0ea933eabd57.dindex.zip.aes,
    removing file listed as Deleting: duplicati-bff73977655174231b9554d1d520df1f3.dblock.zip.aes,
...
]
Warnings: [
    Expected there to be a temporary fileset for synthetic filelist (15, duplicati-20170108T031458Z.dlist.zip.aes), but none was found?
]
Errors: []

### PR DESCRIPTION
**Pull request by seantempleton**
A synthetic filelist could not be uploaded due to the logic in UploadSyntheticFilelist. The code passing in the fileset id to the class would get the id based on if the volume was in the Temporary or Uploading states. If the volume was in the Uploading state, present on the remote backend, and of the right size it would get changed to Uploaded.

One of the first things UploadSyntheticFilelist does is throw an exception if the volume is not in the Uploaded state. Or if it is in the Uploaded state, the next check would prevent a synthetic filelist from being created if the volume was not in the Uploading or Temporary states.

Removed the check for the volume not being in the Uploaded state as the warning in the second check handles that case.

Removed the using statement as it would dispose of the FilesetVolumeWriter after passing it to the UploadChannel. The UploadChannel could not use it since it had been disposed.

Fixed the GetRemoteVolumeFromIDAsync taking a fileset id and matching it up against a volume id. Now it will use fileset id to get the volume that matches the fileset.

Change the StopNow disruption test to not use a synthetic file list. The test was written with it not working and therefore fails a check on the number of filesets after stopping a backup.

Bonus fix for a possible null exception in Dispose for VolumeWriterBase.

Fixes #2506

### CODE REVIEW

File: Duplicati/Library/Main/Database/LocalBackupDatabase.cs [hunk 1]
```diff
@@ -864,19 +864,19 @@ public IRemoteVolume GetRemoteVolumeFromName(string name, System.Data.IDbTransac
...
                 if (rd.Read())
                     return new RemoteVolumeEntry(
-                        id,
-                        rd.GetValue(0).ToString(),
-                        (rd.GetValue(3) == null || rd.GetValue(3) == DBNull.Value) ? null : rd.GetValue(3).ToString(),
-                        rd.ConvertValueToInt64(2, -1),
-                        (RemoteVolumeType)Enum.Parse(typeof(RemoteVolumeType), rd.GetValue(1).ToString()),
-                        (RemoteVolumeState)Enum.Parse(typeof(RemoteVolumeState), rd.GetValue(4).ToString()),
-                        new DateTime(rd.ConvertValueToInt64(5, 0), DateTimeKind.Utc)
+                        int.Parse(rd.GetValue(0).ToString()),
```
Comment (kenkendk) [inline Duplicati/Library/Main/Database/LocalBackupDatabase.cs]: I think you need to use `rd.ConvertValueToInt64(0, -1)`.
This fixes problems with reading values larger than `2^32` and handles eventual `null` values.

**Comment by kenkendk** [comment]
Other than my comment about the integer conversion, I think this looks good and can be merged.

File: Duplicati/Library/Main/Database/LocalBackupDatabase.cs (hunk 1 above)
Comment (seantempleton) [reply Duplicati/Library/Main/Database/LocalBackupDatabase.cs]: Done

**Comment by warwickmm** [comment]
I'll merge this so that we can update pull request #4049 with these dependencies.
