### PR TITLE
Avoid null reference exception when building Sia error messages

### LINKED ISSUE #4193: Error Checking Sia Connection
- [ x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Ubuntu 20.04 LTS
- **Backend**: Sia

## Description
When pressing the Test button for creating a new Sia backup, I get the message " Object reference not set to an instance of an object"

## Steps to reproduce
Create a new Sia backup, fill out details, press Test.

- **Actual result**:
>  Object reference not set to an instance of an object
- **Expected result**:
Returns a success code, or possibly an error one.

## Debug log
```
System.NullReferenceException: Object reference not set to an instance of an object
  at Duplicati.Library.Backend.Sia.Sia.getResponseBodyOnError (System.String context, System.Net.WebException wex) [0x0000c] in <14e57604c2324616af9b95b6901484d2>:0 
  at Duplicati.Library.Backend.Sia.Sia.GetFiles () [0x000cd] in <14e57604c2324616af9b95b6901484d2>:0 
  at Duplicati.Library.Backend.Sia.Sia+<List>d__26.MoveNext () [0x00021] in <14e57604c2324616af9b95b6901484d2>:0 
  at Duplicati.Library.Interface.BackendExtensions.TestList (Duplicati.Library.Interface.IBackend backend) [0x00017] in <fcf6c74b3a9546efbbb1e9dfb993a4e1>:0 
  at Duplicati.Library.Backend.Sia.Sia.Test () [0x00000] in <14e57604c2324616af9b95b6901484d2>:0 
  at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection (System.String url, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) [0x000b7] in <c5f097a49c0a4f1fb0f93cf3f5f218b1>:0 
  at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.POST (System.String key, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) [0x00094] in <c5f097a49c0a4f1fb0f93cf3f5f218b1>:0 
  at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) [0x00289] in <c5f097a49c0a4f1fb0f93cf3f5f218b1>:0 
```

### PR DESCRIPTION
**Pull request by warwickmm**
If the resource does not provide an error response, the `WebException.Response` property will be null.

https://docs.microsoft.com/en-us/dotnet/api/system.net.webexception.response?view=netframework-4.7.1

This fixes #4193.

### CODE REVIEW

File: Duplicati/Library/Backend/Sia/Sia.cs [hunk 1]
```diff
@@ -83,6 +83,11 @@ private System.Net.HttpWebRequest CreateRequest(string endpoint)
 
         private string getResponseBodyOnError(string context, System.Net.WebException wex)
         {
+            if (wex.Response is null)
```
Comment (kenkendk) [inline Duplicati/Library/Backend/Sia/Sia.cs:86]: Should this be `if (wex.Response as System.Net.HttpWebResponse == null)` ?
Then it would also catch cases where the response is a netwtork error, rather than crash on the casting.

Maybe consider rewriting it as:
```csharp
var response = wex.Response as System.Net.HttpWebResponse;
if (response == null)
  return $"{context} failed with error: {wex.Message}";

```

Comment (warwickmm) [reply Duplicati/Library/Backend/Sia/Sia.cs]: Yes, good idea.  Revision 0d991d571266a322f01898c133a771ebd290b8d4 refines the check.
